import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  methodologySidebar: [
    {
      type: 'doc',
      id: 'overview/index',
      label: 'Overview',
    },
    {
      type: 'doc',
      id: 'manifiesto',
      label: 'Manifesto',
    },
    {
      type: 'category',
      label: 'Principles',
      link: {type: 'doc', id: 'principles/index'},
      items: [{type: 'autogenerated', dirName: 'principles'}],
    },
    {
      type: 'category',
      label: 'Phases',
      link: {type: 'doc', id: 'phases/index'},
      items: [{type: 'autogenerated', dirName: 'phases'}],
    },
  ],
  frameworkSidebar: [
    {
      type: 'category',
      label: 'Phases',
      link: {type: 'doc', id: 'framework/index'},
      items: [{type: 'autogenerated', dirName: 'framework/phases'}],
    },
    {
      type: 'doc',
      id: 'framework/artifacts',
      label: 'Artifacts',
    },
    {
      type: 'doc',
      id: 'framework/proceso-fase-4',
      label: 'Phase 4 Process',
    },
  ],
  resourcesSidebar: [
    {
      type: 'doc',
      id: 'resources/index',
      label: 'Resources',
    },
    {
      type: 'doc',
      id: 'resources/faq',
      label: "FAQ's",
    },
    {
      type: 'doc',
      id: 'resources/glossary',
      label: 'Glossary',
    },
    {
      type: 'doc',
      id: 'resources/tools',
      label: 'Tools',
    },
  ],
};

export default sidebars;
