import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  methodologySidebar: [
    {
      type: 'category',
      label: 'Overview',
      link: {type: 'doc', id: 'overview/index'},
      items: [{type: 'autogenerated', dirName: 'overview'}],
    },
    {
      type: 'category',
      label: 'Principles',
      link: {type: 'doc', id: 'principles/index'},
      items: [{type: 'autogenerated', dirName: 'principles'}],
    },
    {
      type: 'category',
      label: 'Phases',
      link: {type: 'doc', id: 'phases/index'},
      items: [{type: 'autogenerated', dirName: 'phases'}],
    },
  ],
  frameworkSidebar: [
    {
      type: 'category',
      label: 'Framework',
      link: {type: 'doc', id: 'framework/index'},
      items: [{type: 'autogenerated', dirName: 'framework'}],
    },
    {
      type: 'category',
      label: 'Commercial Model',
      link: {type: 'doc', id: 'commercial/index'},
      items: [{type: 'autogenerated', dirName: 'commercial'}],
    },
    {
      type: 'category',
      label: 'Planning',
      link: {type: 'doc', id: 'planning/index'},
      items: [{type: 'autogenerated', dirName: 'planning'}],
    },
  ],
  resourcesSidebar: [
    {
      type: 'category',
      label: 'Resources',
      link: {type: 'doc', id: 'resources/index'},
      items: [{type: 'autogenerated', dirName: 'resources'}],
    },
  ],
};

export default sidebars;
