import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  methodologySidebar: [
    {
      type: 'doc',
      id: 'overview/index',
      label: 'Overview',
    },
    {
      type: 'doc',
      id: 'manifiesto',
      label: 'Manifesto',
    },
    {
      type: 'category',
      label: 'Principles',
      link: {type: 'doc', id: 'principles/index'},
      items: [{type: 'autogenerated', dirName: 'principles'}],
    },
    {
      type: 'category',
      label: 'Phases',
      link: {type: 'doc', id: 'phases/index'},
      items: [{type: 'autogenerated', dirName: 'phases'}],
    },
  ],
  frameworkSidebar: [
    {
      type: 'doc',
      id: 'framework/index',
      label: 'Framework',
    },
    {
      type: 'category',
      label: 'Phases',
      link: {type: 'doc', id: 'framework/phases/index'},
      items: [{type: 'autogenerated', dirName: 'framework/phases'}],
    },
    {
      type: 'doc',
      id: 'framework/processes',
      label: 'Processes',
    },
    {
      type: 'doc',
      id: 'framework/artifacts',
      label: 'Artifacts',
    },
  ],
  resourcesSidebar: [
    {
      type: 'category',
      label: 'Resources',
      link: {type: 'doc', id: 'resources/index'},
      items: [{type: 'autogenerated', dirName: 'resources'}],
    },
  ],
};

export default sidebars;
